These are the VFD conf files from https://github.com/ophub/amlogic-s9…
arthur-liberman/vfd-configurations pull request #15
Opened 2023-06-06 20:46 UTC by phodina

Hi,

I found these configuration files for VFD driver/daemon on unofficial repository for Armbian.

The configuration for X96 Max Plus works for me and it would be great to merge them into one.

With the permission of the author.

2023-06-06 22:32 UTC, arthur-liberman requested changes
Can you please rename the files to follow the naming convention that the rest of the vfd files have?

2023-06-06 22:32 UTC, arthur-liberman commented on hk1-x3.conf
This config already exists.

2023-06-06 22:32 UTC, arthur-liberman commented on hk1box.conf
This looks identical to h96max-x3, so maybe redundant?

2023-06-06 22:32 UTC, arthur-liberman commented on t95.conf
Does this [t95m-s905x-vfd](https://github.com/arthur-liberman/vfd-configurations/blob/master/t95m-s905x-vfd.conf) have the wrong config? Or are there multiple S905X variations? I'm pretty sure I still have a S905X T95m, and the config in my repo definitely works.
If this config is correct, please rename it to `t95m-s905x-2-vfd.conf` and I will rename the existing one with `1`.

2023-06-06 22:32 UTC, arthur-liberman commented on t95z-plus.conf
Dup of [t95z-1-vfd.conf](https://github.com/arthur-liberman/vfd-configurations/blob/master/t95z-1-vfd.conf)

2023-06-06 22:32 UTC, arthur-liberman commented on tx3-mini.conf
Please rename to `tanix-tx3-mini-vfd.conf`

2023-06-06 22:32 UTC, arthur-liberman commented on tx3.conf
Same as above

2023-06-06 22:32 UTC, arthur-liberman commented on tx9-pro.conf
Dup [tanix-tx9-pro-vfd.conf](https://github.com/arthur-liberman/vfd-configurations/blob/master/tanix-tx9-pro-vfd.conf)

2023-06-06 22:32 UTC, arthur-liberman commented on whale.conf
> +vfd_gpio_stb='1,10,0'
Considering the controller here is the FD6551, which has a 2-wire interface, I would say that this line is probably incorrect and should be ` vfd_gpio_stb='0,0,0xFF'`

2023-06-06 22:32 UTC, arthur-liberman commented on x92.conf
Dup [x92-vfd.conf](https://github.com/arthur-liberman/vfd-configurations/blob/master/x92-vfd.conf)

2023-06-06 22:32 UTC, arthur-liberman commented on x96max.conf
Same as x96air, maybe worth unifying them?

2023-06-06 22:32 UTC, arthur-liberman commented on x96maxplus.conf
Same as above.

2023-06-06 22:33 UTC, arthur-liberman commented
Thanks for this, but I made some comments, as I can't accept it as-is.

2023-06-09 22:29 UTC, phodina commented on hk1-x3.conf
Removed

2023-06-09 22:29 UTC, phodina commented on hk1box.conf
```
--- hk1box.conf	2023-06-10 00:27:36.961211989 +0200
+++ h96max-x3.conf	2023-06-10 00:27:36.961211989 +0200
@@ -1,6 +1,6 @@
 # This file must be renamed to vfd.conf and placed in the /storage/.config/ folder.
 #
-# HK1Box / Vontar X3 (S905X3) configuration
+# H96 Max X3 (S905X3) configuration
 #--------------------
 #gpio_xxx:
 # [0] 0 = &gpio, 1 = &gpio_ao.
@@ -35,4 +35,4 @@

 vfd_display_type='0x00,0x00,0x00,0x06'

-functions='alarm usb play pause colon lan wlan'
+functions='alarm usb play pause colon eth wifi'
```

Agreed!

2023-06-09 22:30 UTC, phodina commented on t95z-plus.conf
Removed.

2023-06-09 22:31 UTC, phodina commented on tx3-mini.conf
Done!

2023-06-09 22:33 UTC, phodina commented on tx9-pro.conf
```
--- tx9-pro.conf	2023-06-10 00:27:36.961211989 +0200
+++ tanix-tx9-pro-vfd.conf	2023-06-10 00:27:17.505131843 +0200
@@ -1,14 +1,14 @@
 # This file must be renamed to vfd.conf and placed in the /storage/.config/ folder.
 #
-# Tanix TX9 Pro (S912) configuration
+# Tanix TX9 Pro configuration
 #--------------------
 #gpio_xxx:
 # [0] 0 = &gpio, 1 = &gpio_ao.
 # [1] pin number - https://github.com/openSUSE/kernel/blob/master/include/dt-bindings/gpio/meson-gxl-gpio.h
 # [0] Reserved - must be 0.

-vfd_gpio_clk='0,75,0'
-vfd_gpio_dat='0,74,0'
+vfd_gpio_clk='0,76,0'
+vfd_gpio_dat='0,75,0'
 vfd_gpio_stb='0,53,0'

 #chars:
@@ -34,6 +34,3 @@
 # [3] - Controller.

 vfd_display_type='0x00,0x00,0x00,0x00'
-
-#functions='alarm usb play pause colon lan wlan'
-functions=''
```

Are you sure? The `vfd_gpio_clk` and `vfd_gpio_dat` are allocated to different pins.

2023-06-09 22:34 UTC, phodina commented on x92.conf
They are same. So removing

2023-06-09 22:40 UTC, phodina commented on whale.conf
> +vfd_gpio_stb='1,10,0'
Unfortunately I don't own the device and don't have that much experience with this chip. So I modified the config as suggested.

Can be changed back if somebody discovers it does not work.

2023-06-09 22:41 UTC, phodina commented on t95.conf
I can't guarantee the validity of this config as I don't own the device. If you want I can just remove this device and use your configuration.

2023-06-09 22:42 UTC, phodina commented on tx3.conf
Done

2023-06-09 22:50 UTC, phodina commented
Hi @arthur-liberman,

thanks for the review. I've applied most of your points.

2023-06-12 16:23 UTC, arthur-liberman reviewed
Thanks!
Mostly nitpicking, but I'd like names to be consistent. It makes it easier for me to track/find things later.

2023-06-12 16:23 UTC, arthur-liberman commented on h96max-x3-vfd.conf
h96-max-x3-vfd.conf

2023-06-12 16:23 UTC, arthur-liberman commented on hk1box-vfd.conf
hk1-box-vfd.conf

2023-06-12 16:23 UTC, arthur-liberman commented on t95-vfd.conf
t95m-s905x-2-vfd.conf

2023-06-12 16:23 UTC, arthur-liberman commented on tanix-tx3-vfd.conf
There was an older Tanix TX3 box, you overwrote its config.
You can add `tanix-tx3-s905x3-vfd.conf` or add `-2-` before `vfd.conf`

2023-06-12 16:23 UTC, arthur-liberman commented on tx9-pro.conf
Is it a Tanix box?
I think so, it should be `tanix-tx9-pro-2-vfd.conf` and the existing tx9 pro file may be changed to `tanix-tx9-pro-1-vfd.conf`

2023-06-12 22:09 UTC, phodina commented
No problem. I also like consistency at least in names since the component-wise it's a mess on these boxes :-D

2023-06-12 22:19 UTC, arthur-liberman approved these changes

2023-06-12 22:21 UTC, arthur-liberman commented
This is great, thank you.

2023-06-12 22:21 UTC, merged